# NumPy 

## Numerical Python 
Provides an efficient way to store and manipulate arrays
- ndarray provides efficient storage and manipulation of 1d arrays (vectors), (NxM) matrices, higher dimensional datasets


# Getting started with basic Numpy Array


## Create an array

Clobber the namespace so we dont have to np.<name>

In [2]:
from numpy import *

create an np array. you can pass any type of python seq, list tuples etc

In [4]:
a

array([0, 1, 2, 3, 4, 5], dtype=int32)

In [3]:
a = array([0,1,2,3,4,5],dtype=int32)

In [5]:
ad = a.data
list(ad)

[0, 1, 2, 3, 4, 5]

In [5]:
# what type is a
type(a)

numpy.ndarray

In [8]:
# what is the numerica type of the elements in the array
a.dtype

dtype('int32')

In [10]:
# What shape (dimensions) is the array
a.shape

(6,)

In [13]:
# Bytes per element. 32bit integers should be 4 bytes
a.itemsize

4

In [14]:
# Total size in bytes of the array
a.nbytes

24

In [19]:
# Beware of type coercion
# a holds dtypes int32
print(a)
a[0] = 10.38383
print(a)

[10  1  2  3  4  5]
[10  1  2  3  4  5]


In [22]:
x = array([0,1,1.5,3])
y = array([1,2,3,1])

In [23]:
# Do some vector math not for loop math
dy = y[1:] - y[:-1]

%%capture <varname> captures the result of the operation into a var

In [11]:
%%capture timeit_result
%timeit python_list1 = range(1,1000)
%timeit python_list2 = arange(1,1000)

In [12]:
print(timeit_result)

The slowest run took 8.98 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 3: 266 ns per loop
The slowest run took 7.04 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 3: 1.48 us per loop



## Statistical Analysis

In [19]:
data_set = random.random((2,3))
print(data_set)

[[ 0.93613618  0.33032079  0.19598773]
 [ 0.36707494  0.7528012   0.96362384]]


In [18]:
# example of namespace....cant access np.max and builtin max is being used

In [17]:
max(data_set[0]) 


0.95525652078806722